/**
 * Created by rf1804 on 19/02/2020.
 *
 * @format
 */

export const CHECK_INTERNET_CONNECTION = 'CHECK_INTERNET_CONNECTION';
export const CURRENT_COUNTRY_DATA = 'CURRENT_COUNTRY_DATA';
export const SET_VISIBLE = 'SET_VISIBLE';
export const SET_SPOTIFY_TOKEN = 'SET_SPOTIFY_TOKEN';
export const SET_COUNTRY_PLAYLISTS = 'SET_COUNTRY_PLAYLISTS';
